# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gruby}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["fazibear"]
  s.date = %q{2009-11-23}
  s.description = %q{Gadu-Gadu protocol implementation in Ruby language}
  s.email = %q{fazibear@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG.rdoc",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "examples/status.rb",
     "gruby.gemspec",
     "lib/GRuby/GG.rb",
     "lib/GRuby/GG_constants.rb",
     "lib/GRuby/GG_packets.rb",
     "lib/GRuby/GG_utils.rb",
     "lib/gruby.rb",
     "test/test_GRuby.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/fazibear/gruby}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Gadu-Gadu protocol implementation in Ruby language}
  s.test_files = [
    "test/test_helper.rb",
     "test/test_GRuby.rb",
     "examples/status.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

